version: '3.4'

services:
  scrumflushapi:
    image: scrumflushapi
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development